export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";

export const SIDEBAR_SWITCH_TOGGLE = "SIDEBAR_SWITCH_TOGGLE";

export const PAGE_SET = "PAGE_SET";
export const PAGE_SET_CONTENT = "PAGE_SET_CONTENT";

export const THEME_CHANGE = "THEME_CHANGE";
