export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";

export const SIDEBAR_SWITCH_TOGGLE = "SIDEBAR_SWITCH_TOGGLE";

export const SIDEBAR_PAGE_SELECT = "SIDEBAR_PAGE_SELECT";
